apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    app: myapp
    tier: front-end
  namespace: kube-practice
spec:
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        tier: front-end
      namespace: kube-practice
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end