apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
specs:
  containers:
    - name: mongodb
      image: mongo
      env:
        - name: MONGODB_PASSWORD
          value: mongodb_secret-key