apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: kube-practice
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo
      # env:
      #   - name: MONGODB_PASSWORD
      #     value: mongodb_secret-key
