apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-depl1
  labels:
    app: my-app
    tier: front-end
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      name: my-app-rs
      labels:
        app: my-app
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: nginx