apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deplyoment
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: myapp
        image: notebook-frontend:1.0
        ports:
        - containerPort: 3000
        env:
        - name: 
