apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-depl
  labels:
    app: front-end
    tier: frontend
spec:
  selector:
    matchLabels:
      app: front-end
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end
        tier: frontend
    spec:
      containers:
        - name: front-end-app
          image: front-end:1.1.0
          ports:
            - containerPort: 3000
---
#this file works completely fine , can deploy and expose servic efo external service access
apiVersion: v1
kind: Service 
metadata:
  name: app-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: front-end